[package]
name = "statslib"
version = "0.1.1"
authors = ["STEAMROLLER"]

[profile.release]
lto = true

[dependencies]
regex = "0.2"
lazy_static = "1.0"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
