version: 2
jobs:
  build:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - run:
        name: Nightly Build
        command: |
          rustup run nightly rustc --version --verbose
          rustup run nightly cargo --version --verbose
          rustup run nightly cargo build
      - run:
        name: Stable Build
        command: |
          rustup run stable rustc --version --verbose
          rustup run stable cargo --version --verbose
          rustup run stable cargo build
      - run:
        name: Test
        command: |
          rustup run stable cargo test